version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: ui/Dockerfile
    container_name: streamlit-ui
    ports:
      - "8501:8501"
    depends_on:
      - backend